//----------------------------------------------------------------------------
//  System.Linq.Queryable.dll: System.Linq.Queryable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//----------------------------------------------------------------------------
//  The code is automatically generated by the GenCodeNET tool.
//----------------------------------------------------------------------------
//  .NET Core 5.0.9
//----------------------------------------------------------------------------
//  UnitName: DDNC.System.Linq.Queryable
//  Author: ying32
//----------------------------------------------------------------------------

{$IFNDEF DDNCSYSTEMLINQQUERYABLE}
unit DDNC.System.Linq.Queryable;
{$ENDIF}

{$IFDEF FPC}
  {$mode delphi}//{$H+}
  {$modeswitch advancedrecords}
  {$modeswitch prefixedattributes} // Custom attributes feature，fpc3.2.2+
{$ENDIF}

interface

uses
  DDN.Runtime,
  DDNC.System.Private.CoreLib,
  DDNC.System.Linq.Expressions;

type


{ declares }

  DNEnumerableExecutor = interface; // type: System.Linq.EnumerableExecutor, namespace: System.Linq
  DNEnumerableExecutor<T> = interface; // type: System.Linq.EnumerableExecutor`1, namespace: System.Linq
  DNEnumerableQuery = interface; // type: System.Linq.EnumerableQuery, namespace: System.Linq
  DNEnumerableQuery<T> = interface; // type: System.Linq.EnumerableQuery`1, namespace: System.Linq
  DNQueryable = interface; // type: System.Linq.Queryable, namespace: System.Linq


{ objects }

  //-------------namespace: System.Linq----------------
  DNEnumerableExecutorClass = interface(DDNC.System.Private.CoreLib.DNObjectClass)
  ['{C2C4E7F9-B1B2-5F16-815C-8463B732CCA4}']
  end;

  [DNTypeName('System.Linq.EnumerableExecutor')]
  DNEnumerableExecutor = interface(DDNC.System.Private.CoreLib.DNObject)
  ['{AD12EB79-777A-3708-81C1-5B967D700A25}']
  { methods } 

    function GetType: DDNC.System.Private.CoreLib.DNType;
    function ToString: string;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;

  end;

  TDNEnumerableExecutor = class(TDNGenericImport<DNEnumerableExecutorClass, DNEnumerableExecutor>) end;

  //-------------namespace: System.Linq----------------
  DNEnumerableExecutorClass<T> = interface(DNEnumerableExecutorClass)
  ['{020E8CED-B581-522C-9540-523E1ACE7504}']
  { constructors } 

    {class} function init(expression: DDNC.System.Linq.Expressions.DNExpression): DNEnumerableExecutor<T>;

  end;

  [DNTypeName('System.Linq.EnumerableExecutor`1')]
  DNEnumerableExecutor<T> = interface(DNEnumerableExecutor)
  ['{77AF5CAD-FD5B-3175-9E86-20D19C69F61D}']
  { methods } 

    function GetType: DDNC.System.Private.CoreLib.DNType;
    function ToString: string;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;

  end;

  TDNEnumerableExecutor<T> = class(TDNGenericImport<DNEnumerableExecutorClass<T>, DNEnumerableExecutor<T>>) end;

  //-------------namespace: System.Linq----------------
  DNEnumerableQueryClass = interface(DDNC.System.Private.CoreLib.DNObjectClass)
  ['{FF529266-0A7C-53B7-B091-34C2C6DD0014}']
  end;

  [DNTypeName('System.Linq.EnumerableQuery')]
  DNEnumerableQuery = interface(DDNC.System.Private.CoreLib.DNObject)
  ['{B3984AE7-5FC9-3889-B6B3-0D02D7F82AB3}']
  { methods } 

    function GetType: DDNC.System.Private.CoreLib.DNType;
    function ToString: string;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;

  end;

  TDNEnumerableQuery = class(TDNGenericImport<DNEnumerableQueryClass, DNEnumerableQuery>) end;

  //-------------namespace: System.Linq----------------
  DNEnumerableQueryClass<T> = interface(DNEnumerableQueryClass)
  ['{CBB9EBEA-055E-5E6F-BAD7-53658571B3D5}']
  { constructors } 

    {class} function init(enumerable: DDNC.System.Private.CoreLib.DNIEnumerable<T>): DNEnumerableQuery<T>; overload;
    {class} function init(expression: DDNC.System.Linq.Expressions.DNExpression): DNEnumerableQuery<T>; overload;

  end;

  [DNTypeName('System.Linq.EnumerableQuery`1')]
  DNEnumerableQuery<T> = interface(DNEnumerableQuery)
  ['{039F3D1B-2D1E-3F71-856F-5323A3A9C7DB}']
  { methods } 

    function ToString: string;
    function GetType: DDNC.System.Private.CoreLib.DNType;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;

  end;

  TDNEnumerableQuery<T> = class(TDNGenericImport<DNEnumerableQueryClass<T>, DNEnumerableQuery<T>>) end;

  //-------------namespace: System.Linq----------------
  DNQueryableClass = interface(DDNC.System.Private.CoreLib.DNObjectClass)
  ['{57B77178-733B-50F7-A871-87CAB8F49626}']
  { static methods } 

    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Double>>): DDNC.System.Private.CoreLib.DNNullable<Double>; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNDecimal>): DDNC.System.Private.CoreLib.DNDecimal; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<DDNC.System.Private.CoreLib.DNDecimal>>): DDNC.System.Private.CoreLib.DNNullable<DDNC.System.Private.CoreLib.DNDecimal>; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<Int32>): Int32; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Int32>>): DDNC.System.Private.CoreLib.DNNullable<Int32>; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<Int64>): Int64; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Int64>>): DDNC.System.Private.CoreLib.DNNullable<Int64>; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<Single>): Single; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Single>>): DDNC.System.Private.CoreLib.DNNullable<Single>; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<Double>): Double; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Double>>): DDNC.System.Private.CoreLib.DNNullable<Double>; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNDecimal>): DDNC.System.Private.CoreLib.DNDecimal; overload;
    {class} function Sum(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<DDNC.System.Private.CoreLib.DNDecimal>>): DDNC.System.Private.CoreLib.DNNullable<DDNC.System.Private.CoreLib.DNDecimal>; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<Int32>): Double; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Int32>>): DDNC.System.Private.CoreLib.DNNullable<Double>; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<Int64>): Double; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Int64>>): DDNC.System.Private.CoreLib.DNNullable<Double>; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<Single>): Single; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<DDNC.System.Private.CoreLib.DNNullable<Single>>): DDNC.System.Private.CoreLib.DNNullable<Single>; overload;
    {class} function Average(source: DDNC.System.Linq.Expressions.DNIQueryable<Double>): Double; overload;
    {class} function AsQueryable(source: DDNC.System.Private.CoreLib.DNIEnumerable): DDNC.System.Linq.Expressions.DNIQueryable; overload;

  end;

  [DNTypeName('System.Linq.Queryable')]
  DNQueryable = interface(DDNC.System.Private.CoreLib.DNObject)
  ['{E6166D73-20A7-3D3C-AF55-D54EAD1B7BD0}']
  { methods } 

    function GetType: DDNC.System.Private.CoreLib.DNType;
    function ToString: string;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;

  end;

  TDNQueryable = class(TDNGenericImport<DNQueryableClass, DNQueryable>) end;


implementation


initialization
  LoadAssemblyModule('System.Linq.Queryable.dll', True, 'System.Linq.Queryable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a');

finalization

end.
