//----------------------------------------------------------------------------
//  System.Diagnostics.Tracing.dll: System.Diagnostics.Tracing, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
//----------------------------------------------------------------------------
//  The code is automatically generated by the GenCodeNET tool.
//----------------------------------------------------------------------------
//  .NET Core 2.1.30
//----------------------------------------------------------------------------
//  UnitName: DDNC.System.Diagnostics.Tracing
//  Author: ying32
//----------------------------------------------------------------------------

unit DDNC.System.Diagnostics.Tracing;

{$IFDEF FPC}
  {$mode delphi}//{$H+}
  {$modeswitch advancedrecords}
  {$modeswitch prefixedattributes} // Custom attributes feature，fpc3.2.2+
{$ENDIF}

interface

uses
  DDN.Runtime,
  DDNC.System.Private.CoreLib;

type


{ declares }

  DNEventCounter = interface; // type: System.Diagnostics.Tracing.EventCounter, namespace: System.Diagnostics.Tracing


{ objects }

  //-------------namespace: System.Diagnostics.Tracing----------------
  DNEventCounterClass = interface(DNObjectClass)
  ['{4F31EB79-A3BA-5EA3-B503-31D467786F8A}']
  { constructors } 

    {class} function init(name: string; eventSource: DDNC.System.Private.CoreLib.DNEventSource): DNEventCounter;

  end;

  [DNTypeName('System.Diagnostics.Tracing.EventCounter')]
  DNEventCounter = interface(DDNC.System.Private.CoreLib.DNIDisposable)
  ['{1F3DF042-6945-35E4-A559-52EB582254D0}']
  { methods } 

    procedure WriteMetric(value: Single);
    procedure Dispose;
    function ToString: string;
    function Equals(obj: DDNC.System.Private.CoreLib.DNObject): Boolean;
    function GetHashCode: Int32;
    function GetType: DDNC.System.Private.CoreLib.DNType;

  end;

  TDNEventCounter = class(TDNGenericImport<DNEventCounterClass, DNEventCounter>) end;


implementation


initialization
  InternalTryLoadAssemblyModule('System.Diagnostics.Tracing, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a');

finalization

end.
