//----------------------------------------------------------------------------
//  System.Threading.Tasks.Extensions.dll: System.Threading.Tasks.Extensions, Version=4.3.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
//----------------------------------------------------------------------------
//  The code is automatically generated by the GenCodeNET tool.
//----------------------------------------------------------------------------
//  .NET Core 3.1.18
//----------------------------------------------------------------------------
//  UnitName: DDNC.System.Threading.Tasks.Extensions
//  Author: ying32
//----------------------------------------------------------------------------

{$IFNDEF DDNCSYSTEMTHREADINGTASKSEXTENSIONS}
unit DDNC.System.Threading.Tasks.Extensions;
{$ENDIF}

{$IFDEF FPC}
  {$mode delphi}//{$H+}
  {$modeswitch advancedrecords}
  {$modeswitch prefixedattributes} // Custom attributes feature，fpc3.2.2+
{$ENDIF}

interface

uses
  DDN.Runtime,
  DDNC.System.Private.CoreLib;



{ declares }



{ objects }


implementation


initialization
  LoadAssemblyModule('System.Threading.Tasks.Extensions.dll', True, 'System.Threading.Tasks.Extensions, Version=4.3.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51');

finalization

end.
